// Auth Types
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';

// Family Types
export const FAM_PASS_CHANGED = 'FAM_PASS_CHANGED';
export const FAMILY_FETCH_SUCCESS = 'FAMILY_FETCH_SUCCESS';

// User Types
export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const SELECT_CHILD = 'SELECT_CHILD';
export const MANAGE_POINTS = 'MANAGE_POINTS';
export const ITEMS_FETCH_SUCCESS = 'ITEMS_FETCH_SUCCESS';
export const SELECT_I_CHILD = 'SELECT_I_CHILD';
export const USER_CHORES_FETCH_SUCCESS = 'USER_CHORES_FETCH_SUCCESS';

// Store Types
export const STORE_FETCH_SUCCESS = 'STORE_FETCH_SUCCESS';
export const SELECT_ITEM = 'SELECT_ITEM';
export const RESET_ITEM = 'RESET_ITEM';

// Chore Types
export const CHORE_FETCH_SUCCESS = 'CHORE_FETCH_SUCCESS';
export const SELECT_CHORE = 'SELECT_CHORE';